### ISSUE TITLE
linux: specs for security development

### ISSUE THREAD

**Issue by Friz-zy** [opencontainers/specs#111]
Add spec for developers - what they should implement for security. [Example for Linux](https://github.com/Friz-zy/awesome-linux-containers#security).
Goals:
Right now it hard to find list of features: you have to read source code, descriptions and man pages of another software to get shards of information.

**Comment by philips** [comment]
Can you explain a bit more what you want to see? I think it is reasonable that we link to an external resource around best practices vs trying to provide an all-inclusive resource on designing a chroot.

**Comment by Friz-zy** [comment]
Both variants are better than nothing, right?
It's hard to create to-do from 'scratch' but it would more useful.
External link will be an easier way but it is unlikely that it will give a comprehensive guide.
The first step could be [CIS Docker 1.6 Benchmark v1.0.0](https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf) and [docker-bench-security](https://github.com/docker/docker-bench-security).
Also as I say below I try create my own list from different sources, but I'm not an security specialist =(

**Comment by wking** [comment]
On Tue, Sep 01, 2015 at 12:49:21PM -0700, Filipp Frizzy wrote:
> Both variants are better than nothing, right?

Container security is going to be a large and fluxy field.  If we try
to inline that sort of thing in the spec, I think we'll just end up
with stale recommendations that give folks a false sense of security.
Linking to external docs has the same risk of staleness, but we'd be
investing less effort and a statement the links are use-at-own-risk
suggestions would be close to each individual link.

If someone else wants to take on the burden of maintaining a central
summary of the state-of-the-art in container security, we'd only have
one place to link.  But I think that might be too big a bite for one
group to swallow ;).

**Comment by Friz-zy** [comment]
Yep.

But there is more than 10 years with the appearance of linux kernel features for containers and more than 2 years with the appearance of docker, but security topic began to be discussed only recently. And it is unlikely large number of people will take care about this.

Specification - a place where people want find some best practices. And there is only two famous specs: rocket appc and this one. Appc has a small [note about isolation](https://github.com/appc/spec/blob/master/spec/ace.md#isolators).

This spec claims to be a "open industry standards around container formats and runtime". And it's already contains [short list](https://github.com/opencontainers/specs/blob/master/runtime-config-linux.md) of linux features. Why not add at least a short list of best practices for each?..
And in order to take off false sense of security (and remove from you responsibility), mark this list as not full...

**Comment by mrunalp** [comment]
This is a higher level concern. The spec provides the knobs but it is difficult for two people to agree on what security setting mean high/medium/low for them.
