### ISSUE TITLE
please version opencontainers/specs

### ISSUE THREAD

**Issue by aviau** [opencontainers/specs#151]
Hello,

As I  mentioned in another issue, I am packaging opencontainers/specs for Debian.

We are going to upload a recent commit soon as ``golang-github-opencontainers-specs 0.0~git20150829.0.e9cb564-1``, but we face the issue that runc cannot build with the tip of opencontainers/specs.

Newer versions of Docker also depend on runc, so this has a great impact for us. The fact that runc needs Docker to build puts us in a circular dependencies situation, versioning would help us find stable points where everything builds together.

How far are we from this repository being versioned? This would help us a great deal with the packaging.

**Comment by vbatts** [comment]
this is on my TODOs before next Wednesday. Thanks for the issue! :smile:

**Comment by vbatts** [comment]
https://github.com/opencontainers/specs/releases/tag/v0.1.1 is tagged now, and https://github.com/opencontainers/specs/blob/f6ec7a75c65cd58322ec120f651ccdf465af7973/version.go reflects it.
