### ISSUE TITLE
commit validation broken for merges

### ISSUE THREAD

**Issue by vbatts** [opencontainers/specs#169]
with #167, the merge commit itself failed, so master failed https://travis-ci.org/opencontainers/specs/jobs/79590679
```
The command "$HOME/gopath/bin/golint ./..." exited with 0.
0.33s$ go run .tools/validate.go -range ${TRAVIS_COMMIT_RANGE}
 * 2d9842b Merge pull request #167 from vbatts/validate-dco ... FAIL
  - does not have a valid DCO
 * 8b55acf .tools: repo validation tool ... PASS
1 issues to fix
exit status 1
The command "go run .tools/validate.go -range ${TRAVIS_COMMIT_RANGE}" exited with 1.
```

**Comment by wking** [comment]
On Wed, Sep 09, 2015 at 08:38:15PM -0700, W. Trevor King wrote:
> Wed, Sep 09, 2015 at 08:20:58PM -0700, Vincent Batts:
> > with #167, the merge commit itself failed…
> 
> Just drop a --no-merges into your ‘git log’ calls?

On the other hand, we might want to run some checks for merges
(e.g. Go linting, to make sure nobody broke anything during merge
resolution).  So maybe CommitEntry.Parent should be a
CommitEntry.Parents array, and you should switch off the DCO check
when len(CommitEntry.Parents) > 1.

**Comment by vbatts** [comment]
fair

**Comment by wking** [comment]
Close now that #170 has landed?

**Comment by wking** [comment]
On Mon, Sep 21, 2015 at 11:53:44AM -0700, W. Trevor King wrote:
> Close now that #170 has landed?

Although see also 8831b20 (.travis: Convert TRAVIS_COMMIT_RANGE
base...head to base..head, 2015-09-12, #182, [1]), which would allow
us to run the DCO on only commits in the submitted branch, so we don't
open a DCO-avoidance loophole (“just make a merge commit to dodge the
DCO”).  Probably something that the reviewer would notice, but I think
we want 8831b20 anyway.

[1]: https://github.com/opencontainers/specs/pull/182#issuecomment-139810983
