### ISSUE TITLE
Is PORTS field neccessary for oci specs?

### ISSUE THREAD

**Issue by ChengTiesheng** [opencontainers/specs#178]
The container will listen on the specified network ports at runtime for the purpose of interconnecting, as a result, I think exposed port is important for the container runtime. Is it neccessary to add PORTS field for the specs. Maybe it is appropriate to add Port struct in runtime_config.go.

**Comment by gao-feng** [comment]
I think this job should be done by upper program such as Docker, [Hyper](https://hyper.sh) etc. upper program should manage network itself.

**Comment by vbatts** [comment]
That is a higher level. At best there might could be interface level requests, but not port level.

**Comment by luebken** [comment]
Would you mind elaborating why they shouldn't be on container level?

Both [Docker](https://docs.docker.com/engine/reference/builder/#expose) and [appc](https://github.com/appc/acbuild/blob/master/Documentation/subcommands/port.md) have means of doing so. And I find it reasonable since it gives means of declaring the ports a container listens on.

**Comment by wking** [comment]
On Thu, Mar 17, 2016 at 08:29:13AM -0700, Matthias Lübken wrote:
> Would you mind elaborating why they shouldn't be on container level?

Networking is out-of-scope for the OCI runtime spec.  For more
discussion and suggestions for plugging in a network manager via
hooks, see [1,2].  If you feel inspired to write up a wiki entry
covering that, and a link from this repo to the wiki discussion, I
expect it would get merged [3] (but I'm not a maintainer).

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/3XqoyLqtA6I
     Subject: Do we have any plan for network and storage specs?
     Date: Fri, 14 Aug 2015 02:36:15 -0700 (PDT)
     Message-Id: <c056925e-6ecf-4457-8c16-7ab34d279604@opencontainers.org>
[2]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/9VMBA2dAeuU
     Subject: no vNIC in the container, what is a good default .json template?
     Date: Thu, 10 Dec 2015 12:18:07 -0800 (PST)
     Message-Id: <acbb4587-8d80-452a-8908-446f14a5107c@opencontainers.org>
[3]: whttps://github.com/opencontainers/specs/pull/271#issuecomment-165669973

**Comment by luebken** [comment]
@wking thanks for the pointers. But I'm not so much into the topic that I would feel ready for writing a wiki entry.

I do understand the tension not introducing more areas into this spec like networking. At the same time I feel that declaring what ports a container is listening on would be quite beneficial. And this is independent of the underlying network solution.

@vbatts what do you mean by "interface level" in
> That is a higher level. At best there might could be interface level requests, but not port level.

**Comment by wking** [comment]
On Thu, Mar 24, 2016 at 05:54:31AM -0700, Matthias Lübken wrote:
> At the same time I feel that declaring what ports a container is
> listening on would be quite beneficial.

The runtime won't care about them, but they may be interesting to
higher-level tooling.  With annotations (#331, v0.4.0), you can setup:

  {
    "annotations": {
      "ports": "1,2,3"
    },
    …
  }

in your config.json, although we'd need to land an opaque type [1] to
support something like:

  {
    "annotations": {
      "some-networking-spec": {
        "version": "1.2.3",
        "ports": [80, 443]
      }
    },
    …
  }

with the bundled Go types.

[1]: https://github.com/opencontainers/specs/pull/331/commits/1c49f4d21c3a3c3274ac3da035cb8611182d5905#r55574425
