### ISSUE TITLE
New v0.1.1 tag doesn't match v0.1.0 in version.go

### ISSUE THREAD

**Issue by wking** [opencontainers/specs#183]
We [just tagged v0.1.1][1] yesterday, but I think the plan had been to [make the opening tag v0.1.0][2] (which matches [SemVer's first FAQ entry][3]).  In any event, #173 went with v0.1.0.  It would be nice if the tag and the `version.go` constant matched each other ;), so I'd suggest bumping both to v0.1.2 to avoid any ambiguity.

[1]: https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/dqvRE3zDUIs
[2]: https://github.com/opencontainers/specs/wiki/MeetingMinutes:-2015-09-02
[3]: http://semver.org/

**Comment by vbatts** [comment]
bah..

**Comment by crosbymichael** [comment]
Thanks. Closing because it's not an actionable item now.
