### ISSUE TITLE
Clarify readonlyRootfs

### ISSUE THREAD

**Issue by taylorb-microsoft** [opencontainers/specs#23]
In confid.md:
We should clarify the readonlyRootfs flag.  My interpretation is that when true, writes to that file system from within the container would result in copy on write and when false they would actually modify the underlying file system.  Is that an accurate understanding of the intent?

**Comment by philips** [comment]
That is great question. My interpretation is that readonlyRootfs means it is mounted RO and nothing is writeable, writes will fail.

**Comment by philips** [comment]
@chanezon wrote the original spec, so what was the thought with readonlyRootfs. Perhaps @crosbymichael knows too.

**Comment by wking** [comment]
On Thu, Jun 25, 2015 at 01:01:42PM -0700, Brandon Philips wrote:
> My interpretation is that readonlyRootfs means it is mounted RO and
> nothing is writeable, writes will fail.

That was my interpretation too.  If you want the CoW semantics, just
copy your container before launching it and don't set readonlyRootfs.
For bonus points, using something like btrfs' snapshots for this
initial copy will mean you get to share unaltered blocks between your
copy and the original.

That said, I agree that disambiguation is good, and “mounted
read-only” is pretty unambiguous ;).

**Comment by taylorb-microsoft** [comment]
Makes since, I'll try to disambiguate.   Is this a feature utilized commonly today?  Windows does not support booting/running the OS from read-only volumes so this would have to be a platform split at least for now.

**Comment by wking** [comment]
On Thu, Jun 25, 2015 at 03:32:56PM -0700, Taylor Brown wrote:
> Is this a feature utilized commonly today?

I don't know how to get a number for that, but the ability to do this
in Docker landed in 1.5 [1], and the associated PR
(docker/docker#10093) references docker/docker#7923 (“Fedora has
supported the concept of a readonly root for a long time…).  The other
referenced issues (docker/docker#2710 and docker/docker#8752) seem to
be more focused on the general ideas of increased security and the
fact that you'll fail early if your application tries to store
information in a volume that you don't intend to save.

[1]: https://blog.docker.com/2015/02/docker-1-5-ipv6-support-read-only-containers-stats-named-dockerfiles-and-more/

**Comment by taylorb-microsoft** [comment]
Interesting, seems like the initial conversation was skeptical on it's usefulness but I do like the idea of it interims of failing deterministically if the process tires to write outside of the intended/defined scope.  I submitted https://github.com/opencontainers/specs/pull/25 to try and cleanup/disambiguate the content.
