### ISSUE TITLE
linux-config: clean-up namespaces docs

### ISSUE THREAD

**Issue by philips** [opencontainers/specs#24]
The docs don't reflect things we discussed in-person:

- Adding the path field
- Making the namespaces OS specific
- Plumbing through the hooks to make changes to the namespace

@crosbymichael volunteered for this one I think.

**Comment by mrunalp** [comment]
@philips I can take on the hooks portion of it (talked with @crosbymichael today and he told me look into it). I have assigned myself to #20

**Comment by philips** [comment]
@mrunalp Can you also document the restrictions on joining namespaces from a new user namespace that was discussed? I believe @LK4D4 had details and maybe even linux code/doc references we can use.

**Comment by mrunalp** [comment]
@philips Yes, sure. @LK4D4 and I discussed how a hook would have to be provided to allow customization of other namespaces from a user namespace. @LK4D4 could help review that :)

**Comment by philips** [comment]
@mrunalp Can you get a draft of your current thinking up sometime tomorrow?

**Comment by mrunalp** [comment]
There are PRs open for the first two items for Linux. I will put up a draft for the namespaces tomorrow.

**Comment by vbatts** [comment]
discussed during review.
