### ISSUE TITLE
 Spec should have a reference to RFC2119 

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/specs#256]
For clarity purposes the words like MUST should be defined by the spec. For example:

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.. link: http://tools.ietf.org/html/rfc2119

**Comment by wking** [comment]
On Tue, Nov 24, 2015 at 02:36:55PM -0800, Mike Brown wrote:
> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT",
> "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this
> document are to be interpreted as described in RFC 2119.. link:
> http://tools.ietf.org/html/rfc2119

+1.

**Comment by philips** [comment]
+1. We should probably have some huge flag day where we agree to make these
changes.

**Comment by vbatts** [comment]
:+1:

**Comment by wking** [comment]
This can probably be closed now that #260 has landed.
