### ISSUE TITLE
Container dependencies

### ISSUE THREAD

**Issue by steveeJ** [opencontainers/specs#27]
At this early stage the specs say that *The goal of a Standard Container is to encapsulate a software component and all its dependencies in a format that is self-describing and portable*.

My interpretation of this passage is that there will be no inter-container dependencies (for Standard Containers). With this issue I would like to ask for an explanation of the current state and bring the matter up for discussion starting with my personal opinion. 

I think that **container dependencies** is a valuable feature that can significantly increase resource efficiency for all processes/states of the container lifecycle. It should be taken into account from the earliest stage possible.

**Comment by crosbymichael** [comment]
This effort is really focused on the single container and pushing things like dependency management to the upper layers because dependencies really depend on the supervisor or orchestration levels consuming a runtime.  

Most daemons like systemd, docker, mesos, etc all handle dependency management between ~containers.  I think it is much simpler to leave this to the higher levels of the stack.

**Comment by taylorb-microsoft** [comment]
I agree with @crosbymichael a separation of responsibilities is important - moreover I might want/need the different containers to run across different container hosts for example.  So while I fully agree policies like dependencies are very important for containers I just don't think (at least at this time) they belong in the container format.

**Comment by steveeJ** [comment]
@crosbymichael Can you confirm that I understand correctly, and containers will be able to have dependencies but their specification doesn't allow to express these?

This implies that there exists a higher level entity and a specification which is understood by all these daemons that you're mentioning. Is there already a name and/or specification of such a high level standardized entity which allows the specification of inter-container dependencies?

*(On a side note: I don't fully agree to put systemd(-nspawn) and docker in the same category as mesos and I would appreciate an answer that clarifies what exactly you're referring to.)*

@taylorb-microsoft Ideally, a dependency does not require an architecture attribute.
 The dependency resolver should be able to pick the correct container according to the container's architecture value. This would be relevant if the dependency specification allows the usage of non-unique attributes (e.g. category/name) which could yield in multiple results representing different architectures.

**Comment by crosbymichael** [comment]
"containers" like applications have dependencies but this is not a concern at the runtime level.  It's a higher level concept and right now the spec and format's scope is runtime.  

Thanks for the issue but at this time we are not ready to look into add dependencies.
