### ISSUE TITLE
Define Spec API best practices

### ISSUE THREAD

**Issue by vishh** [opencontainers/specs#273]
To make contributions easier, as we come up with best practices for the Spec, we should document them.
For example, we decide to use pointers for all fields that need to provide a "do not touch" option.

**Comment by wking** [comment]
+1 from me [1] :).

[1]: https://groups.google.com/a/opencontainers.org/forum/#!searchin/dev/maintainer/dev/CbiDx1WpleI/CRydJ8HZGAAJ
     Subject: Recording style and policy in opencontainers/specs
     Date: Wed, 9 Sep 2015 11:09:29 -0700
     Message-ID: <20150909180929.GS18140@odin.tremily.us>
