### ISSUE TITLE
Should we add an item in roadmap for network usage for OCI?

### ISSUE THREAD

**Issue by ChengTiesheng** [opencontainers/specs#274]
We have already reached a consensus that network setup is out-of-scope for opencontainers/specs[1], however, I think a detailed guide for user to involve networking with OCI/runC is necessary[2]. Any plan for it? Should we add an item in [roadmap](https://github.com/opencontainers/specs/blob/master/ROADMAP.md)?

[1] https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/3XqoyLqtA6I
[2] https://groups.google.com/a/opencontainers.org/forum/#!topic/dev/zA-E_x5Wuq4

**Comment by philips** [comment]
I don't think OCI needs to cover anything about networking. I think the concerns of a container runtime and container networking are orthogonal and can be solved separately via lifecycle hooks. See for example [Container Networking Interface (CNI)](https://github.com/appc/cni).

I am going to close this for now. If another maintainer disagrees we can reopen.
