### ISSUE TITLE
System properties

### ISSUE THREAD

**Issue by mrunalp** [opencontainers/specs#28]
We have key=value pairs that are written to files under the /proc/sys directory in Linux which are exposed as system properties in libcontainer. Does Windows have any such equivalent? I would imagine that registry setting might fit in there. If that is the case, then we could move system properties to the portable portion of the spec.

**Comment by mrunalp** [comment]
@taylorb-microsoft do you have any comments about Windows?

**Comment by philips** [comment]
@mrunalp Does doing this add clarity or improve code sharing? I feel like we should just call it sysctl and put it in the Linux section. There are other key/value things like rlimits but I don't feel it makes sense to smash rlimits and sysctl together.

**Comment by mrunalp** [comment]
@philips I agree with you. I was trying to see if we could somehow add more to the portable section. I guess we can do that over time rather than forcing it now.

**Comment by taylorb-microsoft** [comment]
Windows does have policies, most commonly folks would think of group/local policy as an example of this (run gpedit.msc on any windows machines and you'll see a set of the local policies).  You would use those to specify such things as credential delegation or global networking polices or time servers as examples.  Ultimately those all turn into registry keys so you could see someone wanting to configure them as part of a build script (aka dockerfile) or some other such means as well.

We don't currently have plans to configure these as part of creating/starting a container but its something we could consider adding if customers desired that functionality in the future.

**Comment by crosbymichael** [comment]
This has been resolved by #29
