### ISSUE TITLE
Process.User name is ambiguous

### ISSUE THREAD

**Issue by arcnmx** [opencontainers/specs#281]
As it depends on the platform, `user` would make more sense as `linuxUser` or similar. It may need a different object schema on some other platform (if it exists at all).

**Comment by arcnmx** [comment]
Or alternatively, it may also be moved into the Linux object rather than Process to consolodate platform-specific settings all in one place.

**Comment by jonboulle** [comment]
This is being discussed at length in #191

**Comment by vbatts** [comment]
I agree it's ambiguous and needs improvement. Please carry the conversation on #191 like @jonboulle mentioned
