### ISSUE TITLE
Aims to clarification, adjusts the directory structure for specs.

### ISSUE THREAD

**Issue by ChengTiesheng** [opencontainers/specs#297]
It seems a bit confusing that code is mixed with document in specs.
I think maybe it will be better if we split code and document into different directory.
Because specs("github.com/opencontainers/specs") has been used as a package in external project, maybe we can put *.md files into an independent directory such as "docs".
   
Is it necessary? What about your point of view:-)

**Comment by wking** [comment]
On Mon, Jan 11, 2016 at 05:37:57PM -0800, Tiesheng wrote:
> It seems a bit confusing that code is mixed with document in specs

There is work underway to move the non-normative Go into
subdirectories (#276), which may be what you're after.

**Comment by ChengTiesheng** [comment]
@wking, thanks a lot for your reminder, it is exactly what I want:-)

**Comment by ChengTiesheng** [comment]
Solved, thanks:)
