### ISSUE TITLE
Make container id a required parameter for all runc(client) operations 

### ISSUE THREAD

**Issue by mikebrow** [opencontainers/specs#315]
Per the face to face discussions we decided to make --id, or similar parameter, required for all of the runc operations. 

I'll generate a PR to update the runtime.md docs to specify the need for the container id for each of the runc operations.  In particular, update the lifecyle description.

**Comment by wking** [comment]
On Thu, Jan 21, 2016 at 03:49:15PM -0800, Mike Brown wrote:
> I'll generate a PR to update the runtimemd docs to specify the need
> for the container id for each of the runc operations In particular,
> update the lifecyle description

It's not my favorite approach [1,2,3], but as of 6f2665a it looks like
this is already done in #225.

[1]: https://github.com/opencontainers/specs/pull/225#issuecomment-172633075
[2]: https://groups.google.com/a/opencontainers.org/d/msg/dev/q6TYqVZOcX8/W1RVyCXCCQAJ
     Subject: Re: removal of /run/opencontainer/containers, add --state?
     Date: Tue, 8 Dec 2015 15:49:57 -0800
     Message-ID: <20151208234957.GK2767@odin.tremily.us>
[3]: https://github.com/wking/oci-command-line-api/pull/14

**Comment by mikebrow** [comment]
Ah I see.. been ill for a bit just getting back into it.  Thx Trevor will close.

**Comment by duglin** [comment]
I think a PR for runc is still needed though and we should just make it a normal arg, not a flag.  
ie. `runc <action> <id> ...`
