### ISSUE TITLE
spec.go: move Go types to this repository

### ISSUE THREAD

**Issue by crosbymichael** [opencontainers/specs#42]
We should move the initial `spec.go` `spec_linux.go` to this repository.  This allow validation tools to be built to check and/or generate documentation along with configuration.  It also allows anyone writing OCF tools in Go to have the types in one repository that they can import and feel confident that they are correct and follow the spec.

**Comment by mrunalp** [comment]
:+1:

**Comment by stevvooe** [comment]
:+1:

Check out how we use templates to generate specification details in docker/distribution. It ensures that the code and specification can't get out of sync.

**Comment by crosbymichael** [comment]
I'm working on moving these types today
