### ISSUE TITLE
Allow joining cgroups of another container

### ISSUE THREAD

**Issue by mrunalp** [opencontainers/specs#68]
The spec allows specifying namespace fds via paths and that feature allows one container to share the namespaces of another container. Another feature to make that more useful is allowing a container to join the cgroups of another container using its pid. This will make it possible for higher level tooling to add nsinit/nsenter like functionality.

@crosbymichael @philips WDYT?

**Comment by philips** [comment]
Why not use the cgroup name?

**Comment by mrunalp** [comment]
@philips That works, too. I think there should be a way to solve the use case.

**Comment by philips** [comment]
@mrunalp Wait, sorry, what information would you add on top of the kernel metadata? e.g. `/proc/571/cgroup`

**Comment by wking** [comment]
On Tue, Jul 28, 2015 at 12:05:54PM -0700, Brandon Philips wrote:
> @mrunalp Wait, sorry, what information would you add on top of the
> kernel metadata? e.g. `/proc/571/cgroup`

In the absence of further information here, I think we can close this
issue once #137 lands.

**Comment by mrunalp** [comment]
Yes, we can close this with #137.

**Comment by wking** [comment]
#137 has landed.  Close?
