### ISSUE TITLE
Separate linux-specific config from os-independent config

### ISSUE THREAD

**Issue by philips** [opencontainers/specs#7]
Moving opencontainers/runc#2 here:

As discussed, we like the idea of having 2 different kinds of configuration in the manifest: 1) os-specific config (for example: create a new pid namespace, or set cgroup foo to bar, or drop CAP_SYSADMIN), and 2) os-independent config (for example: execute /bin/bash, or set environment DEBUG to 1).

Currently these 2 different kinds of configs are mixed in the manifest. We should segment them more clearly, to make more visible the tradeoff between control and portability, and to allow for new sections to be created for other OSes - Windows, Solaris, FreeBSD etc.

**Comment by philips** [comment]
Where we ended up on this one is we will have a strongly typed OS specific section in the spec like `"linux": {}` or `"windows": {}`.

**Comment by tnachen** [comment]
This looks like is already done?

**Comment by philips** [comment]
@tnachen Where do you see it as done? Neither the spec nor the [implementation](https://github.com/opencontainers/runc/blob/master/spec_linux.go#L83) have been updated.

**Comment by crosbymichael** [comment]
Yep, `"linux": {}` is that we want

**Comment by tnachen** [comment]
Sorry I saw config-linux.md and I thought that is what this is for.

**Comment by philips** [comment]
This is figured out in runc/spec_linux.go now.
