### ISSUE TITLE
checks, tests and style

### ISSUE THREAD

**Issue by vbatts** [opencontainers/specs#90]
golint, go tests, etc. 

* [x] Set up some kind of CI (travis?)
* [x] ensure the code conforms to [`golint`](https://github.com/golang/lint)
* [x] enable `go test ./...` in CI
* [x] enable `golint` in CI
* [x] validate DCO

**Comment by vbatts** [comment]
there are no `_test.go` to test yet, so that doesn't make sense yet. But golint and setting up CI is good to do now.

**Comment by wking** [comment]
On Mon, Aug 03, 2015 at 07:33:11AM -0700, Vincent Batts wrote:
> But golint and setting up CI is good to do now.

Yes please :).

I just noticed that 73bf1ba8 (JSON objects are easier to
parse/manipulate, 2015-08-27, #120) landed without a Signed-off-by
tag, despite the README requiring one by that point [1].  Anyhow, if
we do decide to enforce things like this, I think we should be running
a CI service like Travis so we don't forget to check.

[1]: https://github.com/opencontainers/specs/blob/73bf1ba8332dfa7fedd9b1535101894146e958ea/README.md#sign-your-work
     Actually, the README just explains what the Signed-off-by tag
     means, but it doesn't seem to *require* contributed commits to
     contain a sign-off.  The DCO docs landed with 84707b08 (Add
     license and DCO information for contributions, 2015-07-02, #54),
     and reading through that PR it appears the intention was to
     require a sign-off.

**Comment by vbatts** [comment]
I've found where travis needed authorization for my membership in opencontainers. That's been requested now.

**Comment by vbatts** [comment]
Also, #154 got the golint squared up.

**Comment by vbatts** [comment]
Working up a DCO validator right now.

**Comment by vbatts** [comment]
Thanks @crosbymichael for enabling travis.
Now only to merge #167 and we can close out this issue too.
