### ISSUE TITLE
Minor: Change name of github organization to "Open Container Initiative" 

### ISSUE THREAD

**Issue by luebken** [opencontainers/specs#97]
The github organization should be renamed "Open Container Initiative" since:

> *We originally named this effort “Open Container Project,” or OCP. Given the potential for confusion with the awesome Open Compute Project,” we have renamed this the Open Container Initiative or OCI."

http://blog.docker.com/2015/07/open-container-format-progress-report/

Link to settings for maintainer convenience: https://github.com/organizations/opencontainers/settings/profile

**Comment by chanezon** [comment]
Good point. Done.
